Pecunia MVC with EF/Pecunia.PresentationMVC/Models/CarLoanApply.cs
using Capgemini.Pecunia.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Pecunia.PresentationMVC.Models
{
    public class CarLoanApplyModel
    {
        public Guid? LoanID { get; set; } // system generated 

        [Required(ErrorMessage = "This field can't be blank")]
        [RegularExpression("^[0-9a-fA-F-]{36}$", ErrorMessage = "Customer Id not valid")]
        public Guid? CustomerID { get; set; } //user input 

        [Required(ErrorMessage = "This field can't be blank")]
        [Range(100000, 2000000, ErrorMessage = "Minimum Amount Rs.1 lakh and Maximum amount Rs.20 lakh")]
        public decimal? AmountApplied { get; set; } // user input

        [Required(ErrorMessage = "This field can't be blank")]
        [Range(1,120, ErrorMessage = "Minimum Repayment Period one month and maximum Repayment Period 180 months")]
        public byte? RepaymentPeriod { get; set; } //user input

        [Required(ErrorMessage = "This field can't be blank")]
        public string Occupation { get; set; } //user input

        [Required(ErrorMessage = "This field can't be blank")]
        [Range(10000, 10000000, ErrorMessage = "Minimum income Rs.10000/month and Maximum income Rs.1cr/month")]
        public decimal? GrossIncome { get; set; } //user input 

        [Required(ErrorMessage = "This field can't be blank")]
        [Range(1, 9999999, ErrorMessage = "Deductions can not be negative")]
        public decimal? SalaryDeductions { get; set; } //user input

        [Required(ErrorMessage = "This field can't be blank")]
        public string Vehicle { get; set; } //user input 

        [Required(ErrorMessage = "Please accepts the terms and conditions")]
        public bool IsAccepted { get; set; }

    }
}

Pecunia MVC with EF/Pecunia.PresentationMVC/Controllers/CarLoanApplyController.cs
using Capgemini.Pecunia.BusinessLayer;
using Capgemini.Pecunia.BusinessLayer.LoanBL;
using Capgemini.Pecunia.Entities;
using Pecunia.PresentationMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Pecunia.PresentationMVC.Controllers
{
    public class CarLoanApplyController : Controller
    {
        // URL: CarLoanApply/apply
        //[Route("carapply/apply")]
        public ActionResult Apply()
        {
            CarLoanApplyModel carLoanApplyModel = new CarLoanApplyModel();
            //getting list of customers
            CustomerBL customerBL = new CustomerBL();
            List<DropDownListData> customers = new List<DropDownListData>();
            customers = GetDropDownListData();
            System.Diagnostics.Debug.WriteLine("loanID:" + carLoanApplyModel.LoanID);

            ViewBag.customers = new SelectList(customers, "ID", "NameMobile");
            return View(carLoanApplyModel);
        }


        [HttpPost]
        public async Task<ActionResult> Apply(CarLoanApplyModel carLoanModel)
        {
            CarLoanBL carLoanBL = new CarLoanBL();
            CarLoan carLoan = new CarLoan();

            carLoan.LoanID = Guid.NewGuid();
            carLoan.CustomerID = carLoanModel.CustomerID;
            carLoan.AmountApplied = carLoanModel.AmountApplied;
            carLoan.RepaymentPeriod = carLoanModel.RepaymentPeriod;
            carLoan.Occupation = carLoanModel.Occupation;
            carLoan.GrossIncome = carLoanModel.GrossIncome;
            carLoan.SalaryDeduction = carLoanModel.SalaryDeductions;
            carLoan.VehicleType = carLoanModel.Vehicle;
            
            bool isApplied = await carLoanBL.ApplyLoanBL(carLoan);
            if (isApplied == true)
                return RedirectToAction("ViewDetails", "CarLoanView", new { loanID = carLoan.LoanID });
            else
                return RedirectToAction("DisplayMessage", "ShowMessage", new { Message= "Salary deductions must be less than Gross Income"});

        }


        List<DropDownListData> GetDropDownListData()
        {
            List<DropDownListData> list = new List<DropDownListData>();
            using (PecuniaEntities pecEnt = new PecuniaEntities())
            {
                list = (from cust
                        in pecEnt.Customers
                        select new DropDownListData
                        {
                            ID = cust.CustomerID,
                            NameMobile = "Name:" + cust.CustomerName + "|Mobile:" + cust.CustomerMobile
                        }).ToList();
            }
            return list;
        }

    }


}

Pecunia MVC with EF/Pecunia.PresentationMVC/Views/CarLoanApply/apply.cshtml
@model Pecunia.PresentationMVC.Models.CarLoanApplyModel
@using System.Web.Optimization

@{
    ViewBag.Title = "apply";
    Layout = "~/Views/Shared/LoanNavBar.cshtml";
}

@Scripts.Render("~/scripts/jqueryBundle")
@Scripts.Render("~/scripts/validatorBundle")
@Scripts.Render("~/scripts/bootstrapBundle")
<title>Apply Car Loan</title>
<link href="~/Content/bootstrap.css" rel="stylesheet" />

@using (Html.BeginForm("Apply", "CarLoanApply", FormMethod.Post))
{
    <div class="row pb-3 pl-md-2 bg-info" style="height:80px; width:100%"><h2>Apply Car Loan</h2></div>

    <div class="row" style="background-color:#ddd8b9">
        <div class="form-group col-md-6 mx-auto" style="background-color:#ddd8b9">
            <div class="form-row pt-2">
                @Html.LabelFor(temp => temp.LoanID, new { @class = "col-form-label col-lg-3", text = "Loan ID" })
                <div class="col-lg-9">
                    @Html.TextBoxFor(temp => temp.LoanID, new { @class = "form-control", placeholder = "ID will be generated once you finished the form!", disabled = "true" })
                </div>

            </div>
            <div class="form-row pt-2">
                @Html.LabelFor(temp => temp.CustomerID, new { @class = "col-form-label col-lg-3" })
                <div class="col-lg-9">
                    @Html.DropDownListFor(t => t.CustomerID, ViewBag.customers as SelectList, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-row pt-2">
                @Html.LabelFor(temp => temp.AmountApplied, new { @class = "col-form-label col-lg-3" })
                <div class="col-lg-9">
                    @Html.TextBoxFor(temp => temp.AmountApplied, new { @class = "form-control ", placeholder = "Rs.", type = "number" })
                    @Html.ValidationMessageFor(temp => temp.AmountApplied)
                </div>
            </div>
            <div class="form-row pt-2">
                @Html.LabelFor(temp => temp.RepaymentPeriod, new { @class = "col-form-label col-lg-3" })
                <div class="col-lg-7">
                    @Html.TextBoxFor(temp => temp.RepaymentPeriod, new { @class = "form-control ", placeholder = "Months", type = "number" })

                </div>
                <div class="text-nowrap col-lg-2"> @Html.ValidationMessageFor(temp => temp.RepaymentPeriod)</div>
            </div>
            <div class="form-row pt-2">
                @Html.LabelFor(temp => temp.Occupation, new { @class = "col-form-label col-lg-3" })
                @Html.DropDownListFor(temp => temp.Occupation,
                    new List<SelectListItem>()
                    {
                        new SelectListItem() { Text="Agriculture", Value="AGRICULTURE"},
                        new SelectListItem() { Text="Service", Value="SERVICE"},
                        new SelectListItem() { Text="Self Employed", Value="SELF_EMPLOYED"},
                        new SelectListItem() { Text="Retired", Value="RETIRED"},
                        new SelectListItem() { Text="Others", Value="OTHERS"},
                    }
               )
            </div>
            <div class="form-row pt-2">
                @Html.LabelFor(temp => temp.GrossIncome, new { @class = "col-form-label col-lg-3" })
                <div class="col-lg-9">
                    @Html.TextBoxFor(temp => temp.GrossIncome, new { @class = "form-control col-lg-6", placeholder = "Rs.", type = "number" })
                    @Html.ValidationMessageFor(temp => temp.GrossIncome)
                </div>
            </div>
            <div class="form-row pt-2">
                @Html.LabelFor(temp => temp.SalaryDeductions, new { @class = "col-form-label col-lg-3" })
                <div class="col-lg-9">
                    @Html.TextBoxFor(temp => temp.SalaryDeductions, new { @class = "form-control", placeholder = "Rs.", type = "number" })
                    <span class="text-danger">@Html.ValidationMessageFor(temp => temp.SalaryDeductions)</span>
                </div>
            </div>
            <div class="form-row pt-2">
                @Html.LabelFor(temp => temp.Vehicle, new { @class = "col-form-label col-lg-3 " })
                @Html.DropDownListFor(temp => temp.Vehicle,
                    new List<SelectListItem>()
                    {
                        new SelectListItem() { Text="Two Wheeler", Value="TWO_WHEELER"},
                        new SelectListItem() { Text="Three Wheeler", Value="THREE_WHEELER"},
                        new SelectListItem() { Text="Multi Axle", Value="MULTI_AXLE"},
                        new SelectListItem() { Text="Others", Value="OTHERS"},
                    }
               )
            </div>

            <div class="  pt-3">
                <button class="btn btn-success text-right" data-toggle="tooltip" data-html="true" title="one click away from applying">Submit</button>
            </div>

        </div>
    </div>
}