Pecunia MVC with EF/Pecunia.PresentationMVC/Controllers/CarLoanApproveController.cs
using Capgemini.Pecunia.BusinessLayer.LoanBL;
using Capgemini.Pecunia.Entities;
using Pecunia.PresentationMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;

namespace Pecunia.PresentationMVC.Controllers
{
    public class CarLoanApproveController : Controller
    {
        // GET: ApproveLoan
        public async Task<ActionResult> ListAllCarLoans()
        {
            List<CarLoan> carLoans = new List<CarLoan>();
            
            List<CarLoanViewModel> carLoanViewModels = new List<CarLoanViewModel>();
            
            CarLoanBL carLoanBL = new CarLoanBL();
            
            carLoans = await carLoanBL.ListAllLoansBL();
            
            foreach(CarLoan car in carLoans)
            {
                CarLoanViewModel carLoanViewModel = new CarLoanViewModel()
                {
                    LoanID = car.LoanID,
                    AmountApplied = car.AmountApplied,
                    InterestRate = car.InterestRate,
                    EMI_Amount = car.EMI_amount,
                    RepaymentPeriod = car.RepaymentPeriod,
                    DateOfApplication = car.DateOfApplication,
                    Status = car.LoanStatus,
                    Occupation = car.Occupation,
                    GrossIncome = car.GrossIncome,
                    SalaryDeductions = car.SalaryDeduction,
                    Vehicle = car.VehicleType
                };
                carLoanViewModels.Add(carLoanViewModel);
            }

            
            return View("ApproveCarLoan", carLoanViewModels);
        }


        
        // to update status of loans
        [HttpPost]
        public async Task<ActionResult> UpdateStatus(List<CarLoanViewModel> carLoanModels)
        {

            CarLoanBL carLoanBL = new CarLoanBL();
            List<CarLoan> carLoans = new List<CarLoan>();
            carLoans = await carLoanBL.ListAllLoansBL();
            
            for(int i=0; i<carLoans.Count; i++)
            {
                // status from database if different from the status received from view then update
                if (carLoanModels.ElementAt(i).Status.Equals("NotUpdated") == false)
                {
                    if (carLoans.ElementAt(i).LoanStatus.Equals(carLoanModels.ElementAt(i).Status) == false)
                        await carLoanBL.ApproveLoanBL(carLoans.ElementAt(i).LoanID.ToString(), carLoanModels.ElementAt(i).Status);
                }
            }
            
            return RedirectToAction("DisplayMessageForAdmin", "ShowMessage", new { Message = "Status updated successfully!" });
            
        }

        public async Task<ActionResult> ListAllCarLoansToCancel()
        {
            List<CarLoan> carLoans = new List<CarLoan>();

            List<CarLoanViewModel> carLoanViewModels = new List<CarLoanViewModel>();

            CarLoanBL carLoanBL = new CarLoanBL();

            carLoans = await carLoanBL.ListAllLoansBL();

            foreach (CarLoan car in carLoans)
            {
                CarLoanViewModel carLoanViewModel = new CarLoanViewModel()
                {
                    LoanID = car.LoanID,
                    AmountApplied = car.AmountApplied,
                    InterestRate = car.InterestRate,
                    EMI_Amount = car.EMI_amount,
                    RepaymentPeriod = car.RepaymentPeriod,
                    DateOfApplication = car.DateOfApplication,
                    Status = car.LoanStatus,
                    Occupation = car.Occupation,
                    GrossIncome = car.GrossIncome,
                    SalaryDeductions = car.SalaryDeduction,
                    Vehicle = car.VehicleType
                };
                carLoanViewModels.Add(carLoanViewModel);
            }


            return View("CancelCarLoan", carLoanViewModels);
        }

        public async Task<ActionResult> CancelCarLoan(string loanID)
        {

            CarLoanBL carLoanBL = new CarLoanBL();
            List<CarLoan> carLoans = new List<CarLoan>();
            bool isDeleted = await carLoanBL.DeleteLoanEntryBL(loanID);
            //System.Diagnostics.Debug.WriteLine($"loanID:{loanID}, status:{updatedStatus}");

            if (isDeleted == true)
            {
                return RedirectToAction("DisplayMessage", "ShowMessage", new { Message = "Loan Cancelled Successfully!" });
            }
            else
            {
                return RedirectToAction("DisplayMessage", "ShowMessage", new { Message = "Internal error occured! Request cant be processed now, try again later!" });
            }
        }

        //[HttpPost]
        public ActionResult CancelBatchCarLoan(List<CarLoanViewModel> carLoanViewModels)
        {
            //List<CarLoanViewModel> carLoanViewModels = new List<CarLoanViewModel>();
            System.Diagnostics.Debug.WriteLine("dsf"+carLoanViewModels.Count);
            foreach (var car in carLoanViewModels)
            {
                System.Diagnostics.Debug.WriteLine(car.Occupation);
            }

            return RedirectToAction("DisplayMessage", "ShowMessage", new { Message = "Internal error occured! Request cant be processed now, try again later!" });
        }
    }
}

Pecunia MVC with EF/Pecunia.PresentationMVC/Views/CarLoanApprove/ApproveCarLoan.cshtml
@model List<Pecunia.PresentationMVC.Models.CarLoanViewModel>
@using System.Web.Optimization

@{
    ViewBag.Title = "apply";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

@Scripts.Render("~/scripts/jqueryBundle")
@Scripts.Render("~/scripts/validatorBundle")
@Scripts.Render("~/scripts/bootstrapBundle")
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<style type="text/css">
    .textBox {
        width: 150%;
    }
</style>
<title>Approve Car Loan</title>

<h3 class="text-success mx-auto">Approve Car Loans</h3>
<table border="1" class="table table-striped table-sm table-bordered">
    <thead class="table-dark">
        <tr>
            <td>Loan ID</td>
            <td>Amount (Rs.)</td>
            <td>Interest Rate</td>
            <td>EMI Amount(Rs.)</td>
            <td>Repayment Period</td>
            <td style="font-size:small">Application Date</td>
            <td style="font-size:small">Occupation</td>
            <td style="font-size:small">Income(Rs.)</td>
            <td style="font-size:small">Deductions(Rs.)</td>
            <td style="font-size:small">Vehicle</td>
            <td style="font-size:small">Status</td>
            <td>Update</td>
        </tr>
    </thead>
    <tbody>
        @using (Html.BeginForm("UpdateStatus", "CarLoanApprove", FormMethod.Post))
        {

            for (int i = 0; i < Model.Count; i++)
            {
                <tr>
                    <td style="font-size:small">@Html.TextBoxFor(t => Model[i].LoanID, new { @class = "text-wrap ", disabled = "true" })</td>
                    <td style="font-size:small">@Model[i].AmountApplied</td>
                    <td>@Model[i].InterestRate</td>
                    <td>@Model[i].EMI_Amount</td>
                    <td>@Model[i].RepaymentPeriod</td>
                    <td style="font-size:small">@Model[i].DateOfApplication</td>
                    <td style="font-size:small">@Model[i].Occupation</td>
                    <td style="font-size:small">@Model[i].GrossIncome</td>
                    <td style="font-size:small">@Model[i].SalaryDeductions</td>
                    <td style="font-size:small">@Model[i].Vehicle</td>
                    <td style="font-size:small">@Model[i].Status</td>
                    <td class="form-control">
                        @Html.DropDownListFor(t =>  Model[i].Status,
                        new List<SelectListItem>
                            ()
                            {
                            new SelectListItem() { Text="Please Select", Value="NotUpdated"},
                            new SelectListItem() { Text="APPLIED", Value="APPLIED"},
                            new SelectListItem() { Text="PROCESSING", Value="PROCESSING"},
                            new SelectListItem() { Text="APPROVED", Value="APPROVED"},
                            new SelectListItem() { Text="REJECTED", Value="REJECTED"},
                            new SelectListItem() { Text="INVALID", Value="INVALID"},
                            }


                        )

                    </td>


                </tr>
            }
            <tr><td><button>Update All Changes</button></td></tr>
        }

    </tbody>
</table>

Pecunia MVC with EF/Pecunia.PresentationMVC/Views/CarLoanApprove/CancelCarLoan.cshtml
@model List<Pecunia.PresentationMVC.Models.CarLoanViewModel>
@using System.Web.Optimization

@{
    ViewBag.Title = "apply";
    Layout = "~/Views/Shared/LoanNavBar.cshtml";
}

@Scripts.Render("~/scripts/jqueryBundle")
@Scripts.Render("~/scripts/validatorBundle")
@Scripts.Render("~/scripts/bootstrapBundle")
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<title>Cancel Car Loan</title>

@using (Html.BeginForm("CancelBatchCarLoan", "CarLoanApprove", FormMethod.Post))
{

    <h3 class="text-success mx-auto">Cancel Car Loans</h3>
    <table border="1" class="table table-striped table-sm table-bordered">
        <thead class="table-dark">
            <tr>
                <td>Loan ID</td>
                <td>Amount(Rs.)</td>
                <td>Status</td>
                <td>Interest Rate</td>
                <td>EMI Amount(Rs.)</td>
                <td>Repayment Period</td>
                <td>Application Date</td>
                <td>Occupation</td>
                <td>Income(Rs.)</td>
                <td>Deductions(Rs.)</td>
                <td>Vehicle</td>
                <td></td>
            </tr>
        </thead>
        <tbody>
            @*@using (Html.BeginForm())
                {*@
            @for (int i = 0; i < Model.Count; i++)
            {
                <tr>
                    <td style="font-size:small">@Model[i].LoanID</td>
                    <td style="font-size:small">@Model[i].AmountApplied</td>
                    <td>@Model[i].Status</td>
                    <td>@Model[i].InterestRate</td>
                    <td>@Model[i].EMI_Amount</td>
                    <td>@Model[i].RepaymentPeriod</td>
                    <td style="font-size:small">@Model[i].DateOfApplication</td>
                    <td>@Model[i].Occupation</td>
                    <td>@Model[i].GrossIncome</td>
                    <td>@Model[i].SalaryDeductions</td>
                    <td>@Model[i].Vehicle</td>

                    @*<td>
                            @Html.CheckBoxFor(model => model.ElementAt(i).IsSelected)
                        </td>*@
                    <td>
                        <a href="@Url.Action("CancelCarLoan", "CarLoanApprove", new { loanID = Model[i].LoanID })">Cancel</a>
                    </td>
                </tr>
            }
            @*}*@

        </tbody>
    </table>
    @*<td>
            <a href="@Url.Action("CancelBatchCarLoan", "CarLoanApprove", Model)">Cancel</a>
        </td>
        <td>
            <button>Cancel All Selected</button>
        </td>*@
}