Pecunia MVC with EF/Pecunia.PresentationMVC/Controllers/EduLoanApproveController.cs
using Capgemini.Pecunia.BusinessLayer.LoanBL;
using Capgemini.Pecunia.Entities;
using Pecunia.PresentationMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;

namespace Pecunia.PresentationMVC.Controllers
{
    public class EduLoanApproveController : Controller
    {
        // GET: EduLoanApprove
        public async Task<ActionResult> ListAllEduLoans()
        {
            List<EduLoan> eduLoans = new List<EduLoan>();
            List<EduLoanViewModel> eduLoanViewModels = new List<EduLoanViewModel>();
            EduLoanBL eduLoanBL = new EduLoanBL();
            eduLoans = await eduLoanBL.ListAllLoans();

            foreach (EduLoan edu in eduLoans)
            {
                EduLoanViewModel eduLoanViewModel = new EduLoanViewModel()
                {
                    LoanID = edu.LoanID,
                    AmountApplied = edu.AmountApplied,
                    InterestRate = edu.InterestRate,
                    EMI_Amount = edu.EMI_amount,
                    RepaymentPeriod = edu.RepaymentPeriod,
                    DateOfApplication = edu.DateOfApplication,
                    LoanStatus = edu.LoanStatus,
                    Course = edu.Course,
                    InstituteName = edu.InstituteName,
                    StudentID = edu.StudentID,
                    RepaymentHoliday = edu.RepaymentHoliday
                };
                eduLoanViewModels.Add(eduLoanViewModel);
            }

            return View("ApproveEduLoan", eduLoanViewModels);
        }


        // to update status of loans
        [HttpPost]
        public async Task<ActionResult> UpdateStatus(List<EduLoanViewModel> eduLoanModels)
        {

            EduLoanBL eduLoanBL = new EduLoanBL();
            List<EduLoan> eduLoans = new List<EduLoan>();
            eduLoans = await eduLoanBL.ListAllLoans();

            for (int i = 0; i < eduLoans.Count; i++)
            {
                // status from database if different from the status received from view then update
                if (eduLoanModels.ElementAt(i).LoanStatus.Equals("NotUpdated") == false)
                {
                    if (eduLoans.ElementAt(i).LoanStatus.Equals(eduLoanModels.ElementAt(i).LoanStatus) == false)
                        await eduLoanBL.ApproveLoanBL(eduLoans.ElementAt(i).LoanID.ToString(), eduLoanModels.ElementAt(i).LoanStatus);
                }
            }

            return RedirectToAction("DisplayMessageForAdmin", "ShowMessage", new { Message = "Status updated successfully!" });

        }


        ///////////////////////////////////////////////
        public async Task<ActionResult> ListAllEduLoansToCancel()
        {
            List<EduLoan> eduLoans = new List<EduLoan>();
            List<EduLoanViewModel> eduLoanViewModels = new List<EduLoanViewModel>();
            EduLoanBL eduLoanBL = new EduLoanBL();
            eduLoans = await eduLoanBL.ListAllLoans();

            foreach (EduLoan edu in eduLoans)
            {
                EduLoanViewModel eduLoanViewModel = new EduLoanViewModel()
                {
                    LoanID = edu.LoanID,
                    AmountApplied = edu.AmountApplied,
                    InterestRate = edu.InterestRate,
                    EMI_Amount = edu.EMI_amount,
                    RepaymentPeriod = edu.RepaymentPeriod,
                    DateOfApplication = edu.DateOfApplication,
                    LoanStatus = edu.LoanStatus,
                    Course = edu.Course,
                    InstituteName = edu.InstituteName,
                    StudentID = edu.StudentID,
                    RepaymentHoliday = edu.RepaymentHoliday
                };
                eduLoanViewModels.Add(eduLoanViewModel);
            }

            return View("CancelEduLoan",eduLoanViewModels);
        }


        public async Task<ActionResult> CancelEduLoan(string loanID)
        {

            EduLoanBL eduLoanBL = new EduLoanBL();
            List<EduLoan> eduLoans = new List<EduLoan>();
            bool isDeleted = await eduLoanBL.DeleteLoanEntryBL(loanID);
            //System.Diagnostics.Debug.WriteLine($"loanID:{loanID}, status:{updatedStatus}");

            if (isDeleted == true)
            {
                return RedirectToAction("DisplayMessage", "ShowMessage", new { Message = "Loan Cancelled Successfully!" });
            }
            else
            {
                return RedirectToAction("DisplayMessage", "ShowMessage", new { Message = "Internal error occured! Request cant be processed now, try again later!" });
            }
        }
    }
}

Pecunia MVC with EF/Pecunia.PresentationMVC/Views/EduLoanApprove/ApproveEduLoan.cshtml
@model List<Pecunia.PresentationMVC.Models.EduLoanViewModel>
@using System.Web.Optimization

@{
    ViewBag.Title = "apply";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

@Scripts.Render("~/scripts/jqueryBundle")
@Scripts.Render("~/scripts/validatorBundle")
@Scripts.Render("~/scripts/bootstrapBundle")
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<style type="text/css">
    .textBox {
        width: 150%;
    }
</style>
<title>Approve Car Loan</title>

<h3 class="text-success mx-auto">Approve Educational Loans</h3>
<table border="1" class="table table-striped table-sm table-bordered">
    <thead class="table-dark">
        <tr>
            <td>Loan ID</td>
            <td>Amount (Rs.)</td>
            <td>Interest Rate</td>
            <td>EMI Amount(Rs.)</td>
            <td>Repayment Period</td>
            <td style="font-size:small">Application Date</td>
            <td style="font-size:small">Institute Name</td>
            <td style="font-size:small">Student ID</td>
            <td style="font-size:small">Course</td>
            <td style="font-size:small">Status</td>
            <td>Update</td>
        </tr>
    </thead>
    <tbody>
        @using (Html.BeginForm("UpdateStatus", "EduLoanApprove", FormMethod.Post))
        {

            for (int i = 0; i < Model.Count; i++)
            {
                <tr>
                    <td style="font-size:small">@Html.TextBoxFor(t => Model[i].LoanID, new { @class = "text-wrap ", disabled = "true" })</td>
                    <td style="font-size:small">@Model[i].AmountApplied</td>
                    <td>@Model[i].InterestRate</td>
                    <td>@Model[i].EMI_Amount</td>
                    <td>@Model[i].RepaymentPeriod</td>
                    <td style="font-size:small">@Model[i].DateOfApplication</td>
                    <td style="font-size:small">@Model[i].InstituteName</td>
                    <td style="font-size:small">@Model[i].StudentID</td>
                    <td style="font-size:small">@Model[i].Course</td>
                    <td style="font-size:small">@Model[i].LoanStatus</td>
                    <td class="form-control">
                        @Html.DropDownListFor(t =>  Model[i].LoanStatus,
                        new List<SelectListItem>
                            ()
                            {
                            new SelectListItem() { Text="Please Select", Value="NotUpdated"},
                            new SelectListItem() { Text="APPLIED", Value="APPLIED"},
                            new SelectListItem() { Text="PROCESSING", Value="PROCESSING"},
                            new SelectListItem() { Text="APPROVED", Value="APPROVED"},
                            new SelectListItem() { Text="REJECTED", Value="REJECTED"},
                            new SelectListItem() { Text="INVALID", Value="INVALID"},
                            }

                        )

                    </td>


                </tr>
            }
            <tr><td><button>Update All Changes</button></td></tr>
        }

    </tbody>
</table>

Pecunia MVC with EF/Pecunia.PresentationMVC/Views/EduLoanApprove/CancelEduLoan.cshtml
@model List<Pecunia.PresentationMVC.Models.EduLoanViewModel>
@using System.Web.Optimization

@{
    ViewBag.Title = "apply";
    Layout = "~/Views/Shared/LoanNavBar.cshtml";
}

@Scripts.Render("~/scripts/jqueryBundle")
@Scripts.Render("~/scripts/validatorBundle")
@Scripts.Render("~/scripts/bootstrapBundle")

<link href="~/Content/bootstrap.css" rel="stylesheet" />
<title>Cancel Edu Loan</title>

<h3 class="text-success mx-auto">Cancel Educational Loans</h3>
<table border="1" class="table table-striped table-sm table-bordered">
    <thead class="table-dark">
        <tr>
            <td>Loan ID</td>
            <td>Amount(Rs.)</td>
            <td>Status</td>
            <td>Interest Rate</td>
            <td>EMI Amount(Rs.)</td>
            <td>Repayment Period</td>
            <td>Application Date</td>
            <td>Institute Name</td>
            <td>Course</td>
            <td>Student ID</td>
            <td>Repayment Holiday</td>
            <td></td>
        </tr>
    </thead>
    <tbody>
        @using (Html.BeginForm("CancelEduLoan", "EduLoanApprove", FormMethod.Post))
        {
            for (int i = 0; i < Model.Count; i++)
            {
                <tr>
                    <td style="font-size:small">@Model[i].LoanID</td>
                    <td style="font-size:small">@Model[i].AmountApplied</td>
                    <td>@Model[i].LoanStatus</td>
                    <td>@Model[i].InterestRate</td>
                    <td>@Model[i].EMI_Amount</td>
                    <td>@Model[i].RepaymentPeriod</td>
                    <td style="font-size:small">@Model[i].DateOfApplication</td>
                    <td>@Model[i].InstituteName</td>
                    <td>@Model[i].Course</td>
                    <td>@Model[i].StudentID</td>
                    <td>@Model[i].RepaymentHoliday</td>

                    <td>
                        <a href="@Url.Action("CancelEduLoan", "EduLoanApprove", new {loanID = Model[i].LoanID})">Cancel</a>
                        @*<a href="CarLoanApprove/UpdateStatus/@Model[i].LoanID/@Model[i].Status">Update</a>*@
                    </td>
                </tr>
            }
        }

    </tbody>
</table>