Pecunia MVC with EF/Pecunia.PresentationMVC/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Pecunia.Mvc.Models;
using Capgemini.Pecunia.BusinessLayer;
using System.Threading.Tasks;
using Capgemini.Pecunia.Entities;
using Pecunia.PresentationMVC.ServiceReference1;

namespace Pecunia.Mvc.Controllers
{
    public class CustomersController : Controller
    {
        // GET: Customers
        public ActionResult AddCustomers()
        {
            //Creating and initializing viewmodel object

            CustomerViewModel customerViewModel = new CustomerViewModel();

            //calling view and passing viewmodel object to view
            return View(customerViewModel);
        }

        public ActionResult UpdateCustomers()
        {
            //Creating and initializing viewmodel object

            CustomerViewModel customerViewModel = new CustomerViewModel();

            //calling view and passing viewmodel object to view
            return View(customerViewModel);
        }

        public ActionResult CustomersMenu()
        {
            //Creating and initializing viewmodel object
            //Pecunia.Entities.Customer cus = new Entities.Customer;

            CustomerViewModel customerViewModel = new CustomerViewModel();

            //calling view and passing viewmodel object to view
            return View(customerViewModel);
        }

        public ActionResult SearchCustomer()
        {
            //Creating and initializing viewmodel object
            //Pecunia.Entities.Customer cus = new Entities.Customer;

            CustomerViewModel customerViewModel = new CustomerViewModel();

            //calling view and passing viewmodel object to view
            return View(customerViewModel);
        }

        public ActionResult GetAllCustomers()

        {

            //creating and initializing viewmodel object
            List<CustomerViewModel> customerViewModellist = new List<CustomerViewModel>();

            using (TransactionServiceClient customerServiceClient = new TransactionServiceClient())
            {
                CustomerBL customerBL = new CustomerBL();
                List<Customer> customerList = customerBL.GetAllCustomerDetailsBL();

                foreach (var item in customerList)
                {
                    CustomerViewModel customerView = new CustomerViewModel()
                    {
                        CustomerID = item.CustomerID,
                        CustomerName = item.CustomerName,
                        CustomerAddress = item.CustomerAddress,
                        CustomerMobile = item.CustomerMobile,
                        CustomerEmail = item.CustomerEmail,
                        CustomerPan = item.CustomerPan,
                        CustomerAadhaarNumber = item.CustomerAadhaarNumber,
                        CustomGender = item.CustomerGender,
                        DOB = (DateTime)item.DOB
                    };
                    customerViewModellist.Add(customerView);
                }

               
            }



            //calling view and passing viewmodel object to view
            return View(customerViewModellist);
        }

       


        [HttpPost]
        public async Task<ActionResult> Create(CustomerViewModel customerVM)
        {
            //Create object of PersonsBL
            CustomerBL customerBL = new CustomerBL();

            //Creating object of Person EntityModel
            Customer customer = new Customer();
            customer.CustomerName = customerVM.CustomerName;
            customer.CustomerAddress = customerVM.CustomerAddress;
            customer.CustomerMobile = customerVM.CustomerMobile;
            customer.CustomerEmail = customerVM.CustomerEmail;
            customer.CustomerPan = customerVM.CustomerPan;
            customer.CustomerAadhaarNumber = customerVM.CustomerAadhaarNumber;
            customer.DOB = customerVM.DOB;
            customer.CustomerGender = customerVM.CustomGender;


            //Invoke the AddCustomer method BL
             bool isAdded = await customerBL.AddCustomerBL(customer);
            if (isAdded == true)
            {
             
                return Content("Customer added");
            }
            else
            {
              
                return Content("Customer not added");
            }
        }

        public async Task<ActionResult> Update(Guid id)
        {
            Customer customer = new Customer();
            CustomerViewModel cvm = new CustomerViewModel();
            CustomerBL cuBL = new CustomerBL();
            customer = await cuBL.GetCustomerByCustomerIDBL(id);
            cvm.CustomerName = customer.CustomerName;
            cvm.CustomerAddress = customer.CustomerAddress;
            cvm.CustomerMobile = customer.CustomerMobile;
            cvm.CustomerEmail = customer.CustomerEmail;
            cvm.CustomerID = customer.CustomerID;
            cvm.CustomerPan = customer.CustomerPan;
            cvm.CustomerAadhaarNumber = customer.CustomerAadhaarNumber;
            cvm.DOB = Convert.ToDateTime(customer.DOB);
            cvm.CustomGender = customer.CustomerGender;

            return View("UpdateCustomers",cvm);

        }

        [HttpPost]
        public async Task<ActionResult> Update1(FormCollection customerVM)
        {
           
            CustomerBL customerBL = new CustomerBL();

            System.Diagnostics.Debug.WriteLine(customerVM["CustomerID"]);
        

            //Creating object of Person EntityModel
            Customer customer = new Customer();
            Guid.TryParse(customerVM["CustomerID"], out Guid cust);
            customer.CustomerID = cust;

            customer.CustomerName = customerVM["CustomerName"];
            customer.CustomerAddress = customerVM["CustomerAddress"];
            customer.CustomerMobile = customerVM["CustomerMobile"];
            customer.CustomerEmail = customerVM["CustomerEmail"];
            customer.CustomerPan = customerVM["customerPan"];
            customer.CustomerAadhaarNumber = customerVM["CustomerAadhaarNumber"];
            customer.DOB = Convert.ToDateTime(customerVM["DOB"]);
            customer.CustomerGender= customerVM["CustomGender"];
            


            bool isupdated = await customerBL.UpdateCustomerByCustomerIDBL(customer);
            if (isupdated == true)
            {

                return Content("Customer updated");
            }
            else
            {

                return Content("Customer not updated");
            }

        }


    }
}

Pecunia MVC with EF/Pecunia.PresentationMVC/Controllers/LoginController.cs
using Capgemini.Pecunia.BusinessLayer;
using Capgemini.Pecunia.Entities;
using Pecunia.Mvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Pecunia.Mvc.Controllers
{
    public class LoginController : Controller
    {
        // GET: 
        //URL: Login/Index
        public ActionResult Index()
        {
            //creating login view model
            LoginViewModel loginViewModel = new LoginViewModel();

            //passing view model object to view
            return View(loginViewModel);
        }


        //POST 
        //URL: Login/Index
        [HttpPost]
        public async Task<ActionResult> Index(LoginViewModel loginViewModel)
        {
            //if user type is selected as admin
            if(loginViewModel.UserType == "Admin")
            {
                AdminBL adminBL = new AdminBL();
                Admin admin = new Admin();

                //aasigning view model object details to entity model object
                admin.AdminEmail = loginViewModel.Email;
                admin.AdminPassword = loginViewModel.Password;

                //admin object returned from the database
                Admin loginAdmin = await adminBL.GetAdminByEmailAndPasswordBL(admin.AdminEmail, admin.AdminPassword);
                if (loginAdmin != null)
                {
                    //admin home page    
                    Session["adminID"] = loginAdmin.AdminID;
                    return RedirectToAction("AdminIndex","AdminHome", new { adminID = loginAdmin.AdminID});
                }
                else
                {
                    return Content("Admin not found.");
                }
            }
            
            //if user type is selected as employee
            if(loginViewModel.UserType == "Employee")
            {
                EmployeeBL employeeBL = new EmployeeBL();
                Employee employee = new Employee();

                //aasigning view model object details to entity model object
                employee.EmployeeEmail = loginViewModel.Email;
                employee.EmployeePassword = loginViewModel.Password;

                //employee object returned from the database
                Employee loginEmployee = await employeeBL.GetEmployeeByEmailAndPasswordBL(employee.EmployeeEmail, employee.EmployeePassword);
                if(loginEmployee != null)
                {
                    //employee home page
                    Session["employeeID"] = loginEmployee.EmployeeID;
                    return RedirectToAction("EmployeeIndex","EmployeeHome", new { employeeID = loginEmployee.EmployeeID});
                    
                }
                else
                {
                    return Content("Employee not found.");
                }
            }
            else
                return Content("Please select user type");
        }
    }
}

Pecunia MVC with EF/Pecunia.PresentationMVC/Views/Shared/AccountGroupList.cshtml
@{
    Layout = "~/Views/Shared/PecuniaLayout.cshtml";
}

@using System.Web.Optimization
@Scripts.Render("~/scripts/bootstrapBundle")

<div class="row">
    <div class="col-md-2">
        <div class="list-group">
            <a href="#" class="list-group-item list-group-item-action active">
                Accounts Menu
            </a>
            <a href="@Url.Action("Create", "Accounts")" class="list-group-item list-group-item-action">Create Account</a>
            <a href="@Url.Action("Create", "FixedDeposit")" class="list-group-item list-group-item-action">Create Fixed Deposit</a>
            <a href="@Url.Action("EditingAccountMenu", "Accounts")" class="list-group-item list-group-item-action">Update Account</a>
            <a href="@Url.Action("EditingFixedDepositMenu", "FixedDeposit")" class="list-group-item list-group-item-action">Update Fixed Deposit</a>
            <a href="@Url.Action("ShowAllAccount", "Accounts")" class="list-group-item list-group-item-action">Show Accounts</a>
            <a href="@Url.Action("ShowAllFixedDeposit", "FixedDeposit")" class="list-group-item list-group-item-action">Show Fixed Deposits</a>
        </div>
    </div>

    <div class="col-md-10">
        @RenderBody()
    </div>
</div>

Pecunia MVC with EF/Pecunia.PresentationMVC/Views/Shared/AdminLayout.cshtml
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand font-weight-bold" href="#"><h2 class="display-4">Pecunia</h2></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("AdminIndex", "AdminHome")">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("Index", "Employees")">Employees <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index", "Login")">Log Out</a>
            </li>
            <li class="btn-group pt-2">
                <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Approve Loan
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="@Url.Action("ListAllCarLoans", "CarLoanApprove")">Car Loan</a>
                    <a class="dropdown-item" href="@Url.Action("ListAllEduLoans", "EduLoanApprove")">Edu Loan</a>
                    <a class="dropdown-item" href="@Url.Action("ListAllHomeLoans", "HomeLoanApprove")">Home Loan</a>

                </div>
            </li>
        </ul>

    </div>
</nav>

@RenderBody()

Pecunia MVC with EF/Pecunia.PresentationMVC/Views/Shared/LoanNavBar.cshtml
@{
    Layout = "~/Views/Shared/PecuniaLayout.cshtml";
}

@using System.Web.Optimization
@Scripts.Render("~/scripts/bootstrapBundle")

<div class="row">
    <div class="col-md-2">
        <div class="list-group">
            <a href="#" class="list-group-item list-group-item-action active">
                Menu
            </a>

            <div class="btn-group pt-2">
                <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Car Loan
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="@Url.Action("Apply", "CarLoanApply")">Apply</a>
                    <a class="dropdown-item" href="@Url.Action("ListAllCarLoansToCancel", "CarLoanApprove")">Cancel</a>
                    <a class="dropdown-item" href="@Url.Action("ViewCarLoanDetails", "CarLoanView")">View</a>

                </div>
            </div>

            <div class="btn-group pt-2">
                <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Edu Loan
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="@Url.Action("Apply", "EduLoanApply")">Apply</a>
                    <a class="dropdown-item" href="@Url.Action("ListAllEduLoansToCancel", "EduLoanApprove")">Cancel</a>
                    <a class="dropdown-item" href="@Url.Action("ViewEduLoanDetails", "EduLoanView")">View</a>

                </div>
            </div>

            <div class="btn-group pt-2">
                <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Home Loan
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="@Url.Action("Apply", "HomeLoanApply")">Apply</a>
                    <a class="dropdown-item" href="@Url.Action("ListAllHomeLoansToCancel", "HomeLoanApprove")">Cancel</a>
                    <a class="dropdown-item" href="@Url.Action("ViewHomeLoanDetails", "HomeLoanView")">View</a>

                </div>
            </div>




            @*<a href="@Url.Action("ListAllCarLoans", "CarLoanApprove")" class="list-group-item list-group-item-action">Approve  Car Loan</a>
                <a href="@Url.Action("ListAllEduLoans", "EduLoanApprove")" class="list-group-item list-group-item-action">Approve Edu Loan</a>
                <a href="@Url.Action("ListAllHomeLoans", "HomeLoanApprove")" class="list-group-item list-group-item-action">Approve Home Loan</a>*@

        </div>
    </div>

    <div class="col-md-10">
        @RenderBody()
    </div>
</div>

Pecunia MVC with EF/Pecunia.PresentationMVC/Views/Shared/PecuniaLayout.cshtml
@using System.Web.Optimization

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    @*<title>@ViewBag.Title</title>*@
    @Scripts.Render("~/scripts/bootstrapBundle")
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand font-weight-bold" href="#"><h2 class="display-4">Pecunia</h2></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="@Url.Action("EmployeeIndex", "EmployeeHome")">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("CustomersMenu", "Customers")">Customer</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Create","Accounts")">Account</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Transaction")">Transactions</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Apply", "CarLoanApply")">Loans</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Login")">Log Out</a>
                </li>
            </ul>

        </div>
    </nav>

    <div class="container-fluid">
        @RenderBody()
    </div>
    
</body>
</html>